apiVersion: v1
kind: Pod
metadata:
  name: pod-with-host-path
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /var/config
          name: my-host-path-volume
    - name: busybox-container
      image: busybox:latest
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 30; done;"] # prevent busybox from exiting after completion
    volumes:
      - name: my-host-path-volume
        hostPath:
          path: /tmp # the path on the worker node

# keep in mind this is an antipattern in the Kubernetes world as it ties the worker node with the pod and in case the pod dies and gets rescheduled on another pod then it's getting messy
